server:
  port: 8085
feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持

hm:
  swagger:
    title: 交易管理接口文档
    package: com.hmall.trade.controller
  db:
    database: hm-trade
spring:
  rabbitmq:
    host: 192.168.86.130
    port: 5672
    virtual-host: /hamll
    username: hmall
    password: 123